name: Run Shell Script

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Make the script executable
      - name: Make script executable
        run: chmod +x shell-script.sh

      # Run the shell script
      - name: Run the script
        run: ./shell-script.sh

      # Optional: Commit and push the created file (if needed)
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically created file 'lavi'"
          git push
